### ISSUE TITLE
when all are wrong, the numbers are not excluded

### ISSUE THREAD

**Issue by divinity76** [NebuPookins/JS-Mastermind-Solver#3]
Number of colors: 10
Number of pegs: 4
Allow duplicate collors in a guess: NO

4,0,8,9 Right Color & Column: 0 Right Color, Wrong Column: 0

... now the computer should know that 4 and 0 and 8 and 9 are not part of the answer AT ALL, yet, the next question the computer gives me:

1,4,2,5 Right Color & Column:

.. it thought 4 may still be part of the answer, even tho the first answer proved that to be impossible (along with 0 and 8 and 9), that is probably a bug.

screenshot: 
![image](https://user-images.githubusercontent.com/1874996/56458322-5d61c700-6385-11e9-88e3-e78a79b99782.png)

**Comment by NebuPookins** [comment]
You're right, this looks like a bug. Thanks for reporting it!

**Comment by NebuPookins** [comment]
I rewrote the app. I believe the new version does not have this bug. Please reopen this issue if you think the bug is still present.

**Comment by divinity76** [comment]
@NebuPookins while i got your attention, the gh-pages branch is many years old (this was true even before the rewrite commit), mind updating it?

**Comment by NebuPookins** [comment]
My plan is to kill off the `gh-pages` branch. I want github to serve the index.html from the `master` branch, and I believe I've already configured the repo to do that.
