### ISSUE TITLE
Fix this please

### ISSUE THREAD

**Issue by realKatie** [NebuPookins/JS-Mastermind-Solver#4]
Please make it so there is an infinite amount of guesses, because something is wrong and the code hasn't been solved yet.

![Screenshot 2020-01-16 at 8 09 41 PM](https://user-images.githubusercontent.com/59986233/72578613-25e46480-389c-11ea-884c-9ab9127691a1.png)

**Comment by NebuPookins** [comment]
What's the correct answer for these inputs?

**Comment by realKatie** [comment]
Thank you for your quick response!! I actually realized I messed it up and
it was entirely my fault. Thanks for the response!

**Comment by NebuPookins** [comment]
No problem. Thanks for using this software
