### ISSUE TITLE
It ran out of possible combinations.

### ISSUE THREAD

**Issue by circleference** [NebuPookins/JS-Mastermind-Solver#9]
![20230604_160805](https://github.com/NebuPookins/JS-Mastermind-Solver/assets/88536184/ab8e837b-ee1c-4027-a145-dd1f3a270ba1)
Here is the gameplay. I put the right settings and allowed multiple same colors.

**Comment by NebuPookins** [comment]
Thanks for including the gameplay. I think the issue is that during turn 2, the response was 2 yellow pegs (meaning right color but wrong column), but it should have been 1 yellow peg and 1 red peg, since the right-most white peg was placed correctly.

Let me know if I've missed something.

**Comment by circleference** [comment]
> Thanks for including the gameplay. I think the issue is that during turn 2, the response was 2 yellow pegs (meaning right color but wrong column), but it should have been 1 yellow peg and 1 red peg, since the right-most white peg was placed correctly.
> 
> Let me know if I've missed something.

yeah sorry for that I'm the one who missed something.

thx for letting me know tho lol
